# Generated by Django 4.2.29 on 2026-04-13 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(choices=[('key', '자리연습'), ('word', '단어연습'), ('short', '짧은글연습'), ('long', '긴글연습')], max_length=10, verbose_name='연습 유형')),
                ('language', models.CharField(choices=[('ko', '한글'), ('en', '영어')], max_length=10, verbose_name='언어')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('speed', models.IntegerField(default=0, verbose_name='타수 (WPM)')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='정확도 (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-speed', '-created_at'],
            },
        ),
    ]
