# Generated by Django 4.2.29 on 2026-04-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('word', '단어'), ('short', '짧은글'), ('long', '긴글')], max_length=10, verbose_name='콘텐츠 유형')),
                ('language', models.CharField(choices=[('ko', '한글'), ('en', '영어')], max_length=10, verbose_name='언어')),
                ('title', models.CharField(blank=True, help_text='긴글 연습 등에서 제목으로 표시됩니다.', max_length=100, verbose_name='제목')),
                ('text', models.TextField(help_text='단어는 쉼표나 줄바꿈으로 구분, 문장은 줄바꿈으로 구분하세요.', verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '타자연습 콘텐츠',
                'verbose_name_plural': '타자연습 콘텐츠 목록',
            },
        ),
    ]
