# Generated by Django 4.2.29 on 2026-04-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_practice', '0002_typingcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingcontent',
            name='emoji',
            field=models.CharField(blank=True, default='⌨️', max_length=10, verbose_name='이모지'),
        ),
    ]
