# Generated by Django 4.2.29 on 2026-04-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_practice', '0003_typingcontent_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingcontent',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='영어 내용'),
        ),
        migrations.AddField(
            model_name='typingcontent',
            name='text_ja',
            field=models.TextField(blank=True, null=True, verbose_name='일본어 내용'),
        ),
        migrations.AddField(
            model_name='typingcontent',
            name='text_ko',
            field=models.TextField(blank=True, help_text='단어는 쉼표나 줄바꿈으로 구분, 문장은 줄바꿈으로 구분하세요.', null=True, verbose_name='한국어 내용'),
        ),
        migrations.AddField(
            model_name='typingcontent',
            name='text_zh',
            field=models.TextField(blank=True, null=True, verbose_name='중국어 내용'),
        ),
        migrations.AlterField(
            model_name='typingcontent',
            name='language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', '영어'), ('ja', '일본어'), ('zh', '중국어')], default='ko', max_length=10, verbose_name='기본 언어'),
        ),
        migrations.AlterField(
            model_name='typingcontent',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='내용(구)'),
        ),
        migrations.AlterField(
            model_name='typingcontent',
            name='title',
            field=models.CharField(blank=True, help_text='연습 주제 또는 제목', max_length=100, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='typingscore',
            name='language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', '영어'), ('ja', '일본어'), ('zh', '중국어')], max_length=10, verbose_name='언어'),
        ),
    ]
