# Generated by Django 4.2.29 on 2026-04-22 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typing_practice', '0004_typingcontent_text_en_typingcontent_text_ja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingcontent',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='내용(구버전)'),
        ),
        migrations.AlterField(
            model_name='typingcontent',
            name='text_ko',
            field=models.TextField(blank=True, help_text='단어는 쉼표나 줄바꿈으로, 문장은 줄바꿈으로 구분하세요.', null=True, verbose_name='한국어 내용'),
        ),
        migrations.AlterField(
            model_name='typingscore',
            name='accuracy',
            field=models.FloatField(default=0.0, verbose_name='정확도(%)'),
        ),
        migrations.AlterField(
            model_name='typingscore',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='타속(WPM)'),
        ),
        migrations.CreateModel(
            name='TypingHallOfFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ko', '한국어'), ('en', '영어'), ('ja', '일본어'), ('zh', '중국어')], default='ko', max_length=10, verbose_name='언어')),
                ('practice_type', models.CharField(blank=True, choices=[('word', '단어연습'), ('short', '짧은글연습'), ('long', '긴글연습')], max_length=10, null=True, verbose_name='연습 유형')),
                ('category', models.CharField(choices=[('peak_speed', '최강타속마스터'), ('avg_speed', '안정타속마스터'), ('accuracy', '정확도마스터'), ('stamina', '끈기마스터')], max_length=20, verbose_name='레전드 부문')),
                ('record_value', models.FloatField(default=0, verbose_name='기록 값')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('speed', models.IntegerField(default=0, verbose_name='타속')),
                ('accuracy', models.FloatField(default=0, verbose_name='정확도')),
                ('quarter_key', models.CharField(blank=True, max_length=10, verbose_name='갱신 분기')),
                ('achieved_at', models.DateTimeField(verbose_name='기록 일시')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_legends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '타자 명예의 전당',
                'verbose_name_plural': '타자 명예의 전당',
                'unique_together': {('language', 'practice_type', 'category')},
            },
        ),
    ]
