# Generated by Django 4.2.29 on 2026-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_practice', '0005_alter_typingcontent_text_alter_typingcontent_text_ko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typinghalloffame',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='?? ??'),
        ),
        migrations.AlterField(
            model_name='typinghalloffame',
            name='accuracy',
            field=models.FloatField(default=0, verbose_name='???'),
        ),
        migrations.AlterField(
            model_name='typinghalloffame',
            name='achieved_at',
            field=models.DateTimeField(verbose_name='?? ??'),
        ),
        migrations.AlterField(
            model_name='typinghalloffame',
            name='category',
            field=models.CharField(choices=[('peak_speed', '최강타속마스터'), ('avg_speed', '안정타속마스터'), ('accuracy', '정확도마스터'), ('stamina', '끈기마스터')], max_length=20, verbose_name='??? ??'),
        ),
        migrations.AlterField(
            model_name='typinghalloffame',
            name='language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', '영어'), ('ja', '일본어'), ('zh', '중국어')], default='ko', max_length=10, verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='typinghalloffame',
            name='practice_type',
            field=models.CharField(blank=True, choices=[('word', '단어연습'), ('short', '짧은글연습'), ('long', '긴글연습')], max_length=10, null=True, verbose_name='?? ??'),
        ),
        migrations.AlterField(
            model_name='typinghalloffame',
            name='quarter_key',
            field=models.CharField(blank=True, max_length=10, verbose_name='?? ??'),
        ),
        migrations.AlterField(
            model_name='typinghalloffame',
            name='record_value',
            field=models.FloatField(default=0, verbose_name='?? ?'),
        ),
        migrations.AlterField(
            model_name='typinghalloffame',
            name='score',
            field=models.IntegerField(default=0, verbose_name='??'),
        ),
        migrations.AlterField(
            model_name='typinghalloffame',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='??'),
        ),
    ]
