# Generated by GPT-5.5 on 2026-05-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typing_practice', '0006_typinghalloffame_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingUnlockProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ko', '한국어'), ('en', '영어'), ('ja', '일본어'), ('zh', '중국어')], max_length=10, verbose_name='언어')),
                ('key_levels', models.JSONField(blank=True, default=list, verbose_name='자리연습 해제 단계')),
                ('word_unlocked', models.BooleanField(default=False, verbose_name='단어연습 해제')),
                ('short_unlocked', models.BooleanField(default=False, verbose_name='짧은글연습 해제')),
                ('long_unlocked', models.BooleanField(default=False, verbose_name='긴글연습 해제')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_unlock_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '타자연습 해제 진행도',
                'verbose_name_plural': '타자연습 해제 진행도',
                'unique_together': {('user', 'language')},
            },
        ),
    ]
