# Generated by Django 4.2.29 on 2026-04-11 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='장 번호')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='장 제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='장 설명')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='항목 순서')),
                ('key', models.CharField(help_text='예: ex01, prob02', max_length=100, verbose_name='키워드/ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('item_type', models.CharField(choices=[('example', '예제'), ('problem', '실습문제'), ('project', '프로젝트'), ('homework', '과제')], default='example', max_length=50, verbose_name='유형')),
                ('explain_html', models.TextField(blank=True, null=True, verbose_name='설명 (HTML 가능)')),
                ('hint', models.TextField(blank=True, null=True, verbose_name='힌트')),
                ('answer_code', models.TextField(blank=True, null=True, verbose_name='정답 코드')),
                ('expected_output', models.TextField(blank=True, null=True, verbose_name='예상 출력값')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.chapter')),
            ],
            options={
                'ordering': ['chapter', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='프로그램 유형')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '프로그램 유형',
                'verbose_name_plural': '프로그램 유형 목록',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='과정명')),
                ('description', models.TextField(blank=True, verbose_name='과정 설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='learning_programs/', verbose_name='대표 이미지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_programs', to='courses.programtype', verbose_name='유형')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.learningprogram'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, verbose_name='제출한 코드')),
                ('last_output', models.TextField(blank=True, verbose_name='마지막 출력')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('completed', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='LearningEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.learningprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'program')},
            },
        ),
    ]
