# Generated by Django 4.2.29 on 2026-04-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='example_input',
            field=models.TextField(blank=True, null=True, verbose_name='테스트용 입력값'),
        ),
    ]
