# Generated by Django 4.2.29 on 2026-04-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_item_example_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='제출 기한'),
        ),
    ]
