# Generated by Django 4.2.29 on 2026-04-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_item_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='숙제 제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='외부 URL')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='제출 기한')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_items', models.ManyToManyField(blank=True, related_name='assignments', to='courses.item', verbose_name='연결된 문제들')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.learningprogram', verbose_name='관련 과정')),
            ],
            options={
                'verbose_name': '과제(홈플레이)',
                'verbose_name_plural': '과제 목록',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
