# Generated by Django 4.2.29 on 2026-04-15 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_homeworkassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkassignment',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='배정된 학생들'),
        ),
    ]
