# Generated by Django 4.2.29 on 2026-04-25 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_homeworkassignment_assigned_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='파일명')),
                ('file', models.FileField(upload_to='homework/attachments/%Y/%m/', verbose_name='첨부 파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.homeworkassignment')),
            ],
            options={
                'verbose_name': '숙제 첨부 파일',
                'verbose_name_plural': '숙제 첨부 파일',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework/submissions/%Y/%m/', verbose_name='제출 파일')),
                ('note', models.TextField(blank=True, verbose_name='학생 메모')),
                ('status', models.CharField(choices=[('submitted', '제출 완료'), ('revision', '보완 필요'), ('completed', '평가 완료')], default='submitted', max_length=20, verbose_name='제출 상태')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='관리자 평가')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='평가일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.homeworkassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '숙제 제출',
                'verbose_name_plural': '숙제 제출',
                'ordering': ['-updated_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
