# Generated by Django 4.2.29 on 2026-05-09 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogram',
            name='answer_zip',
            field=models.FileField(blank=True, null=True, upload_to='learning_programs/answer_zips/', verbose_name='answer.zip'),
        ),
        migrations.AddField(
            model_name='learningprogram',
            name='picture_zip',
            field=models.FileField(blank=True, null=True, upload_to='learning_programs/picture_zips/', verbose_name='picture.zip'),
        ),
        migrations.CreateModel(
            name='AnswerZipImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='learning_programs/answer_zip_imports/%Y/%m/', verbose_name='answer.zip')),
                ('import_rule', models.CharField(default='top_level_folder_chapter', max_length=50, verbose_name='가져오기 규칙')),
                ('status', models.CharField(choices=[('preview', '미리보기'), ('applied', '적용 완료'), ('failed', '실패')], default='preview', max_length=20, verbose_name='상태')),
                ('preview_data', models.JSONField(blank=True, default=dict, verbose_name='미리보기 데이터')),
                ('message', models.TextField(blank=True, verbose_name='처리 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='적용일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_zip_import_batches', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_zip_import_batches', to='courses.learningprogram')),
            ],
            options={
                'verbose_name': '정답 ZIP 가져오기 배치',
                'verbose_name_plural': '정답 ZIP 가져오기 배치',
                'ordering': ['-created_at'],
            },
        ),
    ]
