# Generated by Django 4.2.29 on 2026-05-16 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_learningprogram_answer_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('example', '예제'), ('objective', '객관식'), ('problem', '실습문제'), ('project', '프로젝트'), ('homework', '과제'), ('olympiad', '사고력 올림피아드')], default='example', max_length=50, verbose_name='유형'),
        ),
        migrations.AlterField(
            model_name='programtype',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='정렬 순서'),
        ),
        migrations.CreateModel(
            name='OlympiadAnswerExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='olympiad/examples/%Y/%m/', verbose_name='예시 답안 이미지')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_examples', to='courses.item')),
            ],
            options={
                'verbose_name': '올림피아드 예시 답안',
                'verbose_name_plural': '올림피아드 예시 답안',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OlympiadAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_image', models.ImageField(upload_to='olympiad/submissions/%Y/%m/', verbose_name='답안 이미지')),
                ('ocr_text', models.TextField(blank=True, verbose_name='OCR 텍스트')),
                ('edited_text', models.TextField(blank=True, verbose_name='수정한 답안')),
                ('feedback', models.TextField(blank=True, verbose_name='피드백')),
                ('status', models.CharField(choices=[('submitted', '제출 완료'), ('reviewed', '검토 완료')], default='submitted', max_length=20, verbose_name='제출 상태')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='제출일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_submissions', to='courses.item')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '올림피아드 답안 제출',
                'verbose_name_plural': '올림피아드 답안 제출',
                'ordering': ['-updated_at'],
                'unique_together': {('item', 'student')},
            },
        ),
    ]
