# Generated by Django 4.2.29 on 2026-05-23 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_alter_item_item_type_alter_programtype_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='하위 문제 번호')),
                ('question_text', models.TextField(verbose_name='문제 내용')),
                ('hint', models.TextField(blank=True, verbose_name='힌트')),
                ('example_answer', models.TextField(blank=True, verbose_name='예시 답안')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='courses.item')),
            ],
            options={
                'verbose_name': '올림피아드 하위 문제',
                'verbose_name_plural': '올림피아드 하위 문제',
                'ordering': ['number'],
                'unique_together': {('item', 'number')},
            },
        ),
        migrations.CreateModel(
            name='OlympiadSubAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='서술형 답안')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='olympiad/sub_answers/%Y/%m/', verbose_name='손글씨 사진')),
                ('upload_token', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='QR 업로드 토큰')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 제출일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_sub_answers', to=settings.AUTH_USER_MODEL)),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_answers', to='courses.olympiadsubquestion')),
            ],
            options={
                'verbose_name': '올림피아드 하위 문제 답안',
                'verbose_name_plural': '올림피아드 하위 문제 답안',
                'ordering': ['sub_question__number'],
                'unique_together': {('sub_question', 'student')},
            },
        ),
    ]
