# Generated by Django 4.2.29 on 2026-05-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_olympiad_sub_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadsubanswer',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI 분석일'),
        ),
        migrations.AddField(
            model_name='olympiadsubanswer',
            name='ai_feedback',
            field=models.TextField(blank=True, verbose_name='AI 피드백'),
        ),
        migrations.AddField(
            model_name='olympiadsubanswer',
            name='ai_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='AI 평가점수'),
        ),
        migrations.AddField(
            model_name='olympiadsubanswer',
            name='ocr_text',
            field=models.TextField(blank=True, verbose_name='OCR 인식 텍스트'),
        ),
        migrations.AddField(
            model_name='olympiadsubquestion',
            name='thinking_type',
            field=models.CharField(blank=True, choices=[('정보이해사고력', '정보이해사고력'), ('창의적문제해결사고력', '창의적문제해결사고력'), ('지식기반사고력', '지식기반사고력'), ('통합맥락적사고력', '통합맥락적사고력'), ('협동적사고력', '협동적사고력'), ('윤리적사고력', '윤리적사고력'), ('표현력', '표현력')], max_length=30, verbose_name='사고력 유형'),
        ),
    ]
