# Generated by Django 4.2.29 on 2026-05-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_sub_question_thinking_type_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadanswerexample',
            name='sub_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_examples', to='courses.olympiadsubquestion'),
        ),
    ]
