# Generated by Django 4.2.29 on 2026-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_olympiad_example_sub_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadsubquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_question_images/', verbose_name='문제 이미지'),
        ),
    ]
