# Generated by Django 4.2.29 on 2026-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_sub_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='문제 공통 이미지'),
        ),
    ]
