# Generated by Django 4.2.29 on 2026-06-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_item_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogram',
            name='roadmap_grade',
            field=models.CharField(blank=True, choices=[('', '미배치'), ('5_kids', '유아 5세'), ('6_kids', '유아 6세'), ('7_kids', '유아 7세'), ('1_elem', '초등 1학년'), ('2_elem', '초등 2학년'), ('3_elem', '초등 3학년'), ('4_elem', '초등 4학년'), ('5_elem', '초등 5학년'), ('6_elem', '초등 6학년'), ('1_mid', '중등 1학년'), ('2_mid', '중등 2학년'), ('3_mid', '중등 3학년'), ('1_high', '고등 1학년'), ('2_high', '고등 2학년'), ('3_high', '고등 3학년')], default='', help_text='로드맵 페이지의 어느 세로 열(학년)에 배치할지 지정합니다.', max_length=20, verbose_name='로드맵 학년'),
        ),
        migrations.AddField(
            model_name='learningprogram',
            name='roadmap_track',
            field=models.PositiveSmallIntegerField(choices=[(0, '미표시'), (1, '블록코딩 & 피지컬'), (2, '텍스트코딩 기초'), (3, 'IT 자격증 & 실무'), (4, '올림피아드 & 알고리즘')], default=0, help_text='로드맵 페이지의 어느 가로 행(트랙)에 배치할지 지정합니다.', verbose_name='로드맵 트랙'),
        ),
    ]
