# Generated by Django 4.2.29 on 2026-06-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_learningprogram_roadmap_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningprogram',
            name='roadmap_grade',
        ),
        migrations.RemoveField(
            model_name='learningprogram',
            name='roadmap_track',
        ),
        migrations.CreateModel(
            name='RoadmapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_track', models.PositiveSmallIntegerField(choices=[(1, '블록코딩 & 피지컬'), (2, '텍스트코딩 기초'), (3, 'IT 자격증 & 실무'), (4, '올림피아드 & 알고리즘')], verbose_name='로드맵 트랙')),
                ('roadmap_grade', models.CharField(choices=[('5_kids', '유아 5세'), ('6_kids', '유아 6세'), ('7_kids', '유아 7세'), ('1_elem', '초등 1학년'), ('2_elem', '초등 2학년'), ('3_elem', '초등 3학년'), ('4_elem', '초등 4학년'), ('5_elem', '초등 5학년'), ('6_elem', '초등 6학년'), ('1_mid', '중등 1학년'), ('2_mid', '중등 2학년'), ('3_mid', '중등 3학년'), ('1_high', '고등 1학년'), ('2_high', '고등 2학년'), ('3_high', '고등 3학년')], max_length=20, verbose_name='로드맵 학년')),
                ('title', models.CharField(max_length=100, verbose_name='과정명')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='과정 설명/소개')),
                ('link_url', models.CharField(blank=True, help_text='예: /courses/program/1/curriculum/ 혹은 외부 URL', max_length=300, verbose_name='연결 링크(선택)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '로드맵 노드',
                'verbose_name_plural': '로드맵 노드 목록',
                'ordering': ['roadmap_track', 'roadmap_grade'],
                'unique_together': {('roadmap_track', 'roadmap_grade')},
            },
        ),
    ]
