# Generated by Django 4.2.29 on 2026-06-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_learningprogram_roadmap_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapnode',
            name='span_width',
            field=models.PositiveSmallIntegerField(default=1, help_text='이 과정이 로드맵 상에서 가로로 몇 칸(학년)을 차지할지 지정합니다. (기본값: 1)', verbose_name='점유 칸 수 (학년 범위)'),
        ),
    ]
