# Generated by Django 4.2.29 on 2026-06-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_roadmapnode_span_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapnode',
            name='next_nodes',
            field=models.ManyToManyField(blank=True, related_name='prev_nodes', to='courses.roadmapnode', verbose_name='다음 연결 과정들'),
        ),
    ]
