# Generated by Django 4.2.29 on 2026-06-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_roadmapnode_next_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapnode',
            name='roadmap_grade',
            field=models.CharField(choices=[('kids_5_7', '유아 5~7세'), ('elem_1_2', '초등 1~2학년'), ('elem_3_4', '초등 3~4학년'), ('elem_5_6', '초등 5~6학년'), ('mid_high', '중고등')], max_length=20, verbose_name='로드맵 학년'),
        ),
    ]
