# Generated by Django 4.2.29 on 2026-06-19 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_roadmapnode_roadmap_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='트랙명')),
                ('badge', models.CharField(blank=True, max_length=50, verbose_name='배지 텍스트 (예: FOUNDATION)')),
                ('color', models.CharField(default='#3b82f6', help_text='예: #3b82f6 또는 rgb값', max_length=50, verbose_name='대표 색상 (헥사코드)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '로드맵 트랙',
                'verbose_name_plural': '로드맵 트랙 목록',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='roadmapnode',
            name='roadmap_track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='courses.roadmaptrack', verbose_name='로드맵 트랙'),
        ),
    ]
