# Generated by Django 4.2.29 on 2026-09-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_finder_recommendation_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finderoption',
            name='value',
            field=models.CharField(choices=[('kids', '유아 (5~7세)'), ('elem_low', '초등 저학년 (1~2학년)'), ('elem_high', '초등 고학년 (3~6학년)'), ('secondary', '중고등'), ('none', '완전 초심자'), ('block', '블록 코딩 경험'), ('text', '텍스트 코딩 경험'), ('logic', '사고력/기초 이해'), ('contest', '대회/올림피아드'), ('app_cert', '포트폴리오/자격증'), ('robot_skill', '로봇 제작/피지컬 컴퓨팅'), ('creative_project', '창작 프로젝트/포트폴리오'), ('career_explore', '진로 탐색'), ('fun', '재미있게 즐기면서 배우기')], max_length=30, verbose_name='선택지 값'),
        ),
        migrations.AlterField(
            model_name='finderrecommendation',
            name='goal',
            field=models.CharField(blank=True, choices=[('', '무관'), ('logic', '사고력/기초 이해'), ('contest', '대회/올림피아드'), ('app_cert', '포트폴리오/자격증'), ('robot_skill', '로봇 제작/피지컬 컴퓨팅'), ('creative_project', '창작 프로젝트/포트폴리오'), ('career_explore', '진로 탐색'), ('fun', '재미있게 즐기면서 배우기')], max_length=30, verbose_name='목표 조건'),
        ),
    ]
