# Generated by Django 4.2.29 on 2026-09-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_finderoption_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requires_coding',
            field=models.BooleanField(default=True, help_text='체크 해제 시 AICE 학습 화면에서 AI Codiny 실습 창 없이 설명 패널만 넓게 보여줍니다 (이론/개념 설명용).', verbose_name='AI Codiny 실습 필요'),
        ),
    ]
