"""메듀테크 AI 교육 프로그램 20선 카탈로그.

tools: 이미 만들어져 있는 AI 프롬프트 도구(AI_PROMPT_CARDS의 key) 중 이 프로그램과 관련된 것.
       비어 있으면 '준비 중' 카드로 표시된다. 도구가 새로 만들어지면 여기에 key만 추가하면 된다.
"""

AI_PROGRAMS = [
    {'no': 1, 'title': '생성형 AI 체험', 'tag': 'AI 기초', 'icon': '💡', 'grades': '초·중·고', 'duration': '90분~2시간',
     'desc': 'ChatGPT, Gemini와 함께 생성형 AI의 원리를 이해하고 다양한 질문과 활용을 체험합니다.', 'tools': []},
    {'no': 2, 'title': 'AI 이미지 크리에이터', 'tag': 'AI 이미지', 'icon': '🎨', 'grades': '초·중·고', 'duration': '90분~2시간',
     'desc': '텍스트로 상상을 표현하는 이미지 생성 AI를 활용해 캐릭터, 제품, 포스터 등을 제작합니다.', 'tools': []},
    {'no': 3, 'title': '나만의 미래직업 AI 아바타', 'tag': '진로교육', 'icon': '🧑‍🚀', 'grades': '초·중·고', 'duration': '2~3시간',
     'desc': '관심 분야와 강점을 분석하고 AI로 미래직업을 탐색하여 나만의 아바타와 직업소개 카드를 제작합니다.',
     'tools': ['future_career_video', 'my_avatar']},
    {'no': 4, 'title': 'AI 광고 크리에이터', 'tag': '콘텐츠 제작', 'icon': '📣', 'grades': '중·고', 'duration': '2~3시간',
     'desc': 'AI로 광고 아이디어, 카피, 이미지, 영상을 제작하여 나만의 광고 영상을 완성합니다.', 'tools': []},
    {'no': 5, 'title': 'AI 영화감독 프로젝트', 'tag': '영상 제작', 'icon': '🎬', 'grades': '중·고', 'duration': '3~6시간',
     'desc': '스토리부터 캐릭터, 영상까지 AI로 제작하는 나만의 단편영화를 만들어봅니다.', 'tools': []},
    {'no': 6, 'title': 'AI 뮤직비디오 제작', 'tag': '음악·영상', 'icon': '🎧', 'grades': '중·고', 'duration': '3시간',
     'desc': 'AI로 가사, 음악, 이미지, 영상을 제작하여 나만의 뮤직비디오를 완성합니다.', 'tools': []},
    {'no': 7, 'title': 'AI 유튜버·쇼츠 크리에이터', 'tag': '미디어 콘텐츠', 'icon': '📺', 'grades': '중·고', 'duration': '2~4시간',
     'desc': 'AI 콘텐츠 아이디어, 대본, 영상, 썸네일까지 제작하여 나만의 유튜브 콘텐츠를 완성합니다.',
     'tools': ['content_finder', 'content_idea_finder', 'content_plan', 'channel_branding']},
    {'no': 8, 'title': 'AI 웹사이트 만들기', 'tag': '바이브코딩', 'icon': '💻', 'grades': '중·고', 'duration': '3~6시간',
     'desc': '코딩을 몰라도 AI와 대화하며 실제 동작하는 웹사이트를 제작합니다.', 'tools': []},
    {'no': 9, 'title': 'AI 게임 제작', 'tag': '게임 개발', 'icon': '🎮', 'grades': '중·고', 'duration': '3~6시간',
     'desc': 'AI와 함께 기획하고 코드를 생성하여 직접 플레이할 수 있는 게임을 만들어봅니다.', 'tools': []},
    {'no': 10, 'title': 'AI 챗봇 만들기', 'tag': 'AI 서비스', 'icon': '💬', 'grades': '중·고', 'duration': '2~4시간',
     'desc': '목적에 맞는 나만의 AI 챗봇을 설계하고 지식을 입력하여 실제 활용 가능한 챗봇을 만듭니다.', 'tools': []},
    {'no': 11, 'title': 'AI 지역문제 해결 프로젝트', 'tag': '문제해결', 'icon': '🌏', 'grades': '중·고', 'duration': '3~6시간',
     'desc': '우리 지역의 문제를 AI로 분석하고 해결 아이디어를 설계하여 서비스 또는 발명품으로 제안합니다.',
     'tools': ['local_problem_finder', 'camp_planner']},
    {'no': 12, 'title': 'AI 창업가 프로젝트', 'tag': '창업·비즈니스', 'icon': '🚀', 'grades': '중·고', 'duration': '3~6시간',
     'desc': '생활 속 불편함에서 아이디어를 발견하고 AI로 브랜드, 로고, 광고까지 기획하여 1분 투자발표를 진행합니다.',
     'tools': ['problem_finder', 'presentation_script']},
    {'no': 13, 'title': 'AI 발명가 프로젝트', 'tag': '발명·메이커', 'icon': '🛠️', 'grades': '초·중·고', 'duration': '3시간',
     'desc': '생활 문제를 찾고 AI와 함께 새로운 발명품의 기능과 디자인을 설계합니다.',
     'tools': ['problem_finder', 'carbon_invention']},
    {'no': 14, 'title': 'AI 뉴스 팩트체크', 'tag': 'AI 윤리·미디어', 'icon': '📰', 'grades': '중·고', 'duration': '90분~2시간',
     'desc': '인터넷과 SNS의 정보를 분석하며 AI의 답변을 비교하고 올바른 정보 판별 방법을 배웁니다.', 'tools': []},
    {'no': 15, 'title': 'AI 이미지 탐정', 'tag': 'AI 윤리', 'icon': '🔎', 'grades': '초·중·고', 'duration': '90분~2시간',
     'desc': '진짜 사진과 AI 생성 이미지를 비교하며 딥페이크와 저작권 문제를 탐구합니다.', 'tools': []},
    {'no': 16, 'title': 'AI 데이터 분석가', 'tag': '데이터 분석', 'icon': '📊', 'grades': '중·고', 'duration': '2~3시간',
     'desc': '실제 데이터를 AI와 함께 분석하고 그래프를 시각화하며 데이터 속 의미를 찾아봅니다.', 'tools': []},
    {'no': 17, 'title': 'AI 과학자 프로젝트', 'tag': '융합과학', 'icon': '🧪', 'grades': '초·중·고', 'duration': '2~3시간',
     'desc': '과학·환경 문제를 AI와 함께 조사하고 새로운 해결 방법을 설계합니다.', 'tools': []},
    {'no': 18, 'title': 'AI 탄소중립 프로젝트', 'tag': '환경·지속가능', 'icon': '🌱', 'grades': '초·중·고', 'duration': '3~6시간',
     'desc': '생활 속 탄소문제를 발견하고 AI로 친환경 아이디어와 발명품을 제작합니다.', 'tools': ['carbon_invention']},
    {'no': 19, 'title': 'AI 진로 면접 체험', 'tag': '진로·취업', 'icon': '🤝', 'grades': '중·고', 'duration': '2시간',
     'desc': '희망 직업을 선정하고 AI 면접관과 모의 면접을 진행하여 자기소개와 피드백을 받아봅니다.', 'tools': []},
    {'no': 20, 'title': 'AI 로봇 프로젝트', 'tag': '로봇·융합', 'icon': '🤖', 'grades': '초·중·고', 'duration': '2~6시간',
     'desc': '로봇의 구조와 센서를 이해하고 AI와 결합된 로봇 프로젝트를 직접 체험합니다.', 'tools': []},
]
