from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('tools/ai-prompts/', views.ai_prompts, name='ai_prompts'),
    path('tools/ai-favorites/', views.ai_favorites, name='ai_favorites'),
    path('tools/login-helper/', views.login_helper, name='login_helper'),
    path('api/login-helper/unlock/', views.api_login_helper_unlock, name='api_login_helper_unlock'),
    path('api/login-helper/lock/', views.api_login_helper_lock, name='api_login_helper_lock'),
    path('api/login-helper/links/', views.api_login_helper_links_save, name='api_login_helper_links_save'),
    path('tools/my-avatar/', views.my_avatar, name='my_avatar'),
    path('tools/team-name/', views.team_name, name='team_name'),
    path('tools/carbon-invention/', views.carbon_invention, name='carbon_invention'),
    path('tools/problem-finder/', views.problem_finder, name='problem_finder'),
    path('tools/local-problem-finder/', views.local_problem_finder, name='local_problem_finder'),
    path('api/local-problems/', views.api_local_problems, name='api_local_problems'),
    path('tools/camp-planner/', views.camp_planner, name='camp_planner'),
    path('tools/presentation-script/', views.presentation_script, name='presentation_script'),
    path('api/presentation-prompt/save/', views.api_presentation_prompt_save, name='api_presentation_prompt_save'),
    path('api/problem/join/', views.api_problem_join, name='api_problem_join'),
    path('api/problem/team-info/', views.api_problem_team_info, name='api_problem_team_info'),
    path('api/problem/update/', views.api_problem_update, name='api_problem_update'),
    path('api/problem/room/<int:room_id>/state/', views.api_problem_room_state, name='api_problem_room_state'),
    path('api/avatar-draft/save/', views.api_avatar_draft_save, name='api_avatar_draft_save'),
    re_path(r'^play/(?P<slug>[-\w]+)/$', views.play, name='play'),
    path('upload/', views.upload, name='upload'),
    path('schedule/', views.schedule_view, name='schedule'),
    path('schedule/timetable/', views.timetable_view, name='timetable'),
    path('admin-services/timetable/', views.timetable_admin_list, name='timetable_admin_list'),
    path('admin-services/timetable/add/', views.timetable_admin_create, name='timetable_admin_create'),
    path('admin-services/timetable/<int:entry_id>/edit/', views.timetable_admin_edit, name='timetable_admin_edit'),
    path('admin-services/timetable/<int:entry_id>/delete/', views.timetable_admin_delete, name='timetable_admin_delete'),
    path('admin-services/timetable/api/save/', views.timetable_admin_api_save, name='timetable_admin_api_save'),
    path('board/notice/', views.board_notice, name='board_notice'),
    path('board/notice/create/', views.board_notice_create, name='board_notice_create'),
    path('board/notice/<int:pk>/', views.board_notice_detail, name='board_notice_detail'),
    path('board/notice/<int:pk>/update/', views.board_notice_update, name='board_notice_update'),
    path('board/notice/<int:pk>/delete/', views.board_notice_delete, name='board_notice_delete'),
    path('board/awards/', views.board_awards, name='board_awards'),
    path('board/awards/create/', views.board_awards_create, name='board_awards_create'),
    path('board/awards/<int:pk>/', views.board_awards_detail, name='board_awards_detail'),
    path('board/awards/<int:pk>/update/', views.board_awards_update, name='board_awards_update'),
    path('board/awards/<int:pk>/delete/', views.board_awards_delete, name='board_awards_delete'),
    path('board/competition-types/', views.board_competition_type, name='board_competition_type'),
    path('board/competition-types/create/', views.board_competition_type_create, name='board_competition_type_create'),
    path('board/competition-types/<int:pk>/', views.board_competition_type_detail, name='board_competition_type_detail'),
    path('board/competition-types/<int:pk>/update/', views.board_competition_type_update, name='board_competition_type_update'),
    path('board/competition-types/<int:pk>/delete/', views.board_competition_type_delete, name='board_competition_type_delete'),
    path('board/contests/', views.board_contest, name='board_contest'),
    path('board/contests/create/', views.board_contest_create, name='board_contest_create'),
    path('board/contests/<int:pk>/', views.board_contest_detail, name='board_contest_detail'),
    path('board/contests/<int:pk>/update/', views.board_contest_update, name='board_contest_update'),
    path('board/contests/<int:pk>/delete/', views.board_contest_delete, name='board_contest_delete'),
    path('api/contests/crawl-thinkcontest/', views.api_crawl_thinkcontest, name='api_crawl_thinkcontest'),

    # 작품 평가단
    path('tools/gallery-vote/', views.gallery_vote, name='gallery_vote'),
    path('tools/gallery-admin/', views.gallery_admin, name='gallery_admin'),
    path('api/gallery/rooms/', views.api_gallery_rooms, name='api_gallery_rooms'),
    path('api/gallery/join/', views.api_gallery_join, name='api_gallery_join'),
    path('api/gallery/state/', views.api_gallery_state, name='api_gallery_state'),
    path('api/gallery/vote/', views.api_gallery_vote, name='api_gallery_vote'),
    path('api/gallery/room/create/', views.api_gallery_room_create, name='api_gallery_room_create'),
    path('api/gallery/room/<int:room_id>/delete/', views.api_gallery_room_delete, name='api_gallery_room_delete'),
    path('api/gallery/room/<int:room_id>/control/', views.api_gallery_control, name='api_gallery_control'),
    path('api/gallery/room/<int:room_id>/stats/', views.api_gallery_room_stats, name='api_gallery_room_stats'),
    path('tools/survey/', views.survey_home, name='survey_home'),
    path('tools/survey/<slug:slug>/', views.survey_detail, name='survey_detail'),
    path('api/survey/<slug:slug>/submit/', views.api_survey_submit, name='api_survey_submit'),
    path('api/survey/<slug:slug>/update/', views.api_survey_update, name='api_survey_update'),
    path('api/survey/<slug:slug>/clone/', views.api_survey_clone, name='api_survey_clone'),
    path('api/survey/<slug:slug>/reset/', views.api_survey_reset, name='api_survey_reset'),
    path('api/survey/create/', views.api_survey_create, name='api_survey_create'),
    path('my-report/', views.my_report, name='my_report'),
    path('my-report/child/<int:child_id>/', views.child_report, name='child_report'),
    path('my-report/student/<int:student_id>/', views.admin_student_report, name='admin_student_report'),
    path('api/attendance/submit/', views.api_submit_attendance, name='api_submit_attendance'),
    path('api/session/refresh/', views.api_refresh_session, name='api_refresh_session'),
    path('board/cert/', views.board_cert, name='board_cert'),
    path('board/cert/create/', views.board_cert_create, name='board_cert_create'),
    path('board/cert/<int:pk>/', views.board_cert_detail, name='board_cert_detail'),
    path('board/cert/<int:pk>/update/', views.board_cert_update, name='board_cert_update'),
    path('board/cert/<int:pk>/delete/', views.board_cert_delete, name='board_cert_delete'),
    path('board/certinfo/', views.board_certinfo, name='board_certinfo'),
    path('board/certinfo/create/', views.board_certinfo_create, name='board_certinfo_create'),
    path('board/certinfo/<int:pk>/', views.board_certinfo_detail, name='board_certinfo_detail'),
    path('board/certinfo/<int:pk>/update/', views.board_certinfo_update, name='board_certinfo_update'),
    path('board/certinfo/<int:pk>/delete/', views.board_certinfo_delete, name='board_certinfo_delete'),
    path('board/certinfo/reorder/', views.board_certinfo_reorder, name='board_certinfo_reorder'),
    path('my-projects/', views.my_projects, name='my_projects'),
    path('project/<int:project_id>/preview/', views.project_preview, name='project_preview'),
    path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    path('project/<int:project_id>/edit/', views.edit_project, name='edit_project'),
    path('project/<int:project_id>/approve/', views.approve_project, name='approve_project'),
    path('classes/', views.public_class_list, name='public_class_list'),
    path('consult/', views.consult_inquiry, name='consult_inquiry'),
    path('terms/', views.terms_of_service, name='terms_of_service'),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('refund-policy/', views.refund_policy, name='refund_policy'),
    path('admin-services/consult-inquiries/', views.consult_inquiry_admin_list, name='consult_inquiry_admin_list'),
    path('admin-services/consult-inquiries/<int:pk>/toggle/', views.consult_inquiry_toggle_handled, name='consult_inquiry_toggle_handled'),
    path('signup/', views.signup, name='signup'),
    path('signup/confirm/<str:token>/', views.confirm_signup_email, name='confirm_signup_email'),
    path('onboarding/', views.social_onboarding, name='social_onboarding'),
    path('social-signup/<str:provider>/', views.social_signup_redirect, name='social_signup_redirect'),
    path('member/upgrade-to-medulab-parent/', views.request_medulab_parent_upgrade, name='request_medulab_parent_upgrade'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/email-confirm/<str:token>/', views.confirm_email_change, name='confirm_email_change'),

    # AJAX endpoints
    path('api/like/<int:project_id>/', views.toggle_like, name='toggle_like'),
    path('api/bookmark/<int:project_id>/', views.toggle_bookmark, name='toggle_bookmark'),
    path('api/analyze-zip/', views.analyze_zip, name='analyze_zip'),
    path('api/check-username/', views.check_username, name='check_username'),
    path('api/search-users/', views.search_users, name='search_users'),
    path('api/search-certinfos/', views.search_certinfos, name='search_certinfos'),
    path('api/search-competition-types/', views.search_competition_types, name='search_competition_types'),
    path('api/analyze-award-image/', views.analyze_award_image, name='analyze_award_image'),

    # 회원 관리 (관리자 전용)
    path('admin-services/members/', views.member_list, name='member_list'),
    path('admin-services/members/add/', views.member_create, name='member_create'),
    path('admin-services/members/<int:user_id>/approve/', views.member_approve, name='member_approve'),
    path('admin-services/members/<int:user_id>/convert-to-inactive/', views.member_convert_to_inactive, name='member_convert_to_inactive'),
    path('admin-services/members/<int:user_id>/convert-to-active/', views.member_convert_to_active, name='member_convert_to_active'),
    path('admin-services/members/<int:user_id>/edit/', views.member_edit, name='member_edit'),
    path('admin-services/members/<int:user_id>/delete/', views.member_delete, name='member_delete'),
    path('admin-services/members/<int:user_id>/link-child/', views.member_link_child, name='member_link_child'),
    path('admin-services/members/<int:user_id>/unlink-child/<int:link_id>/', views.member_unlink_child, name='member_unlink_child'),

    # 일정 관리 (관리자 전용)
    path('admin-services/schedules/', views.schedule_admin_list, name='schedule_admin_list'),
    path('admin-services/schedules/add/', views.schedule_admin_create, name='schedule_admin_create'),
    path('admin-services/schedules/sync-aice/', views.api_sync_aice_schedule, name='api_sync_aice_schedule'),
    path('admin-services/schedules/<int:event_id>/edit/', views.schedule_admin_edit, name='schedule_admin_edit'),
    path('admin-services/schedules/<int:event_id>/delete/', views.schedule_admin_delete, name='schedule_admin_delete'),

    # 수업 관리 (관리자 전용)
    path('admin-services/classes/', views.class_admin_list, name='class_admin_list'),
    path('admin-services/classes/reorder/', views.class_admin_reorder, name='class_admin_reorder'),
    path('admin-services/classes/add/', views.class_admin_create, name='class_admin_create'),
    path('admin-services/classes/<int:class_id>/edit/', views.class_admin_edit, name='class_admin_edit'),
    path('admin-services/classes/<int:class_id>/copy/', views.class_admin_copy, name='class_admin_copy'),
    path('admin-services/classes/<int:class_id>/delete/', views.class_admin_delete, name='class_admin_delete'),
    path('admin-services/classes/<int:class_id>/enroll/', views.class_enroll_student, name='class_enroll_student'),
    path('admin-services/classes/<int:class_id>/unenroll/<int:enrollment_id>/', views.class_unenroll_student, name='class_unenroll_student'),
    path('admin-services/classes/<int:class_id>/generate-invoices/', views.class_admin_generate_invoices, name='class_admin_generate_invoices'),
    path('admin-services/classes/<int:class_id>/attendance/', views.class_admin_attendance, name='class_admin_attendance'),

    # 납부 관리 (관리자 전용)
    path('admin-services/tuition/', views.tuition_admin_dashboard, name='tuition_admin_dashboard'),
    path('admin-services/tuition/<int:invoice_id>/attendance/', views.tuition_invoice_attendance_detail, name='tuition_invoice_attendance_detail'),

    # 학원비 결제 (포트원)
    path('tuition/<int:invoice_id>/checkout/', views.tuition_checkout, name='tuition_checkout'),
    path('tuition/<int:invoice_id>/verify/', views.tuition_verify_payment, name='tuition_verify_payment'),
    path('tuition/webhook/', views.tuition_webhook, name='tuition_webhook'),

    # 배지 관리 (관리자 전용)
    path('admin-services/badges/', views.badge_list, name='badge_list'),
    path('admin-services/badges/add/', views.badge_create, name='badge_create'),
    path('admin-services/badges/<int:badge_id>/edit/', views.badge_edit, name='badge_edit'),
    path('admin-services/badges/<int:badge_id>/delete/', views.badge_delete, name='badge_delete'),

    # 대회/자격 접수 이력 관리
    path('admin-services/exam-registrations/', views.exam_registration_admin, name='exam_registration_admin'),
    path('admin-services/exam-registrations/<int:pk>/delete/', views.exam_registration_delete, name='exam_registration_delete'),
    path('api/search-members/', views.api_search_members, name='api_search_members'),
]
