# Generated by Django 4.2.29 on 2026-04-06 09:28

import arcade.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('icon', models.CharField(default='🎮', max_length=10, verbose_name='아이콘(이모지)')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='작품명')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='슬러그')),
                ('description', models.TextField(max_length=500, verbose_name='작품 소개')),
                ('author_display_name', models.CharField(max_length=50, verbose_name='표시 이름 (예: 김민준 중2)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=arcade.models.project_thumbnail_path, verbose_name='썸네일')),
                ('thumbnail_emoji', models.CharField(default='🎮', max_length=10, verbose_name='썸네일 이모지 (이미지 없을 때)')),
                ('color', models.CharField(default='#1a1a2e', max_length=7, verbose_name='카드 배경색')),
                ('accent', models.CharField(default='#e94560', max_length=7, verbose_name='포인트 색상')),
                ('project_zip', models.FileField(upload_to=arcade.models.project_zip_path, verbose_name='작품 파일 (ZIP)')),
                ('entry_file', models.CharField(default='index.html', help_text='ZIP 안의 메인 파일명 (예: index.html)', max_length=100, verbose_name='시작 파일명')),
                ('project_path', models.CharField(blank=True, max_length=300, verbose_name='압축 해제 경로')),
                ('status', models.CharField(choices=[('pending', '심사중'), ('approved', '승인됨'), ('rejected', '반려됨')], default='pending', max_length=10, verbose_name='상태')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천 작품')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='플레이 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='제작자')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arcade.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '학생 작품',
                'verbose_name_plural': '학생 작품',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='arcade.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='arcade.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '즐겨찾기',
                'verbose_name_plural': '즐겨찾기',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
