# Generated by Django 4.2.29 on 2026-04-06 14:43

import arcade.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, help_text='직접 실행 가능한 외부 URL (예: 원드라이브 공유 링크, GitHub Pages 등)', max_length=500, null=True, verbose_name='외부 링크 URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_zip',
            field=models.FileField(blank=True, null=True, upload_to=arcade.models.project_zip_path, verbose_name='작품 파일 (ZIP)'),
        ),
    ]
