# Generated by Django 4.2.29 on 2026-04-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0004_tag_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, to='arcade.category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, help_text='대용량 파일 다운로드 링크 (원드라이브 공유 링크 등)', max_length=500, null=True, verbose_name='외부 링크 URL'),
        ),
    ]
