# Generated by Django 4.2.29 on 2026-04-15 02:49

import arcade.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0006_project_thumbnail_2_project_thumbnail_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=arcade.models.project_thumbnail_path, verbose_name='썸네일 1'),
        ),
    ]
