# Generated by Django 4.2.29 on 2026-04-16 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0007_alter_project_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', '학생회원'), ('general', '일반회원'), ('medulab_member', '메듀랩회원'), ('medulab_teacher', '메듀랩강사'), ('medulab_staff', '메듀랩스탭')], default='general', max_length=20, verbose_name='회원 유형')),
                ('is_approved', models.BooleanField(default=False, verbose_name='승인 여부')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
            },
        ),
    ]
