# Generated by Django 4.2.29 on 2026-04-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, help_text='표시용 이름입니다. 미설정 시 아이디가 사용됩니다.', max_length=30, verbose_name='닉네임'),
        ),
    ]
