# Generated by Django 4.2.29 on 2026-04-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0009_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='실명'),
        ),
    ]
