# Generated by Django 4.2.29 on 2026-04-22 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0011_emailchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '가입 이메일 인증',
                'verbose_name_plural': '가입 이메일 인증',
                'ordering': ['-created_at'],
            },
        ),
    ]
