# Generated by Django 4.2.29 on 2026-04-22 07:35

import arcade.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0012_signupemailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='project',
            name='entry_file',
            field=models.CharField(default='index.html', help_text='ZIP 내부의 메인 파일명(예: index.html)', max_length=100, verbose_name='시작 파일명'),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, help_text='드라이브나 외부 저장소의 공유 링크를 사용할 수 있습니다.', max_length=500, null=True, verbose_name='외부 링크 URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_zip',
            field=models.FileField(blank=True, null=True, upload_to=arcade.models.project_zip_path, verbose_name='작품 파일(ZIP)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail_emoji',
            field=models.CharField(default='🎮', max_length=10, verbose_name='썸네일 이모지'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, help_text='표시할 이름입니다. 비워 두면 이름, 그다음 아이디를 사용합니다.', max_length=30, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', '학생회원'), ('general', '일반회원'), ('medulab_member', '메듀랩 회원'), ('medulab_teacher', '메듀랩 강사'), ('medulab_staff', '메듀랩 스탭')], default='general', max_length=20, verbose_name='회원 유형'),
        ),
    ]
