# Generated by Django 4.2.29 on 2026-05-07 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_item_item_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0013_userprofile_phone_number_alter_project_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='배지 코드')),
                ('name', models.CharField(max_length=100, verbose_name='배지명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('icon', models.CharField(default='🏅', max_length=10, verbose_name='아이콘')),
                ('color', models.CharField(default='#f5c451', max_length=7, verbose_name='포인트 색상')),
                ('category', models.CharField(choices=[('typing', '타자연습'), ('learning', '학습과정'), ('milestone', '성장기록')], default='milestone', max_length=20, verbose_name='배지 분류')),
                ('criteria_type', models.CharField(blank=True, max_length=50, verbose_name='획득 조건 유형')),
                ('criteria_value', models.PositiveIntegerField(default=1, verbose_name='획득 조건 값')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('related_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completion_badges', to='courses.learningprogram', verbose_name='연결 과정')),
            ],
            options={
                'verbose_name': '배지',
                'verbose_name_plural': '배지',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='획득일')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_users', to='arcade.badge', verbose_name='배지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 배지',
                'verbose_name_plural': '사용자 배지',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
