# Generated by Django 4.2.29 on 2026-05-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0014_badge_userbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='일정명')),
                ('description', models.TextField(blank=True, verbose_name='상세 설명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('event_type', models.CharField(choices=[('holiday', '휴원/공휴일'), ('academic', '학사 일정'), ('competition', '대회'), ('seminar', '특강/세미나')], default='academic', max_length=20, verbose_name='일정 유형')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
            ],
            options={
                'verbose_name': '학원 일정',
                'verbose_name_plural': '학원 일정',
                'ordering': ['start_date', 'end_date', 'title'],
            },
        ),
    ]
