# Generated by Django 4.2.29 on 2026-05-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0015_scheduleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='external_url',
            field=models.URLField(blank=True, help_text='대회 페이지나 관련 자료 링크', max_length=500, verbose_name='링크 URL'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schedule/posters/', verbose_name='이미지 (포스터)'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='end_date',
            field=models.DateTimeField(verbose_name='종료일시'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='event_type',
            field=models.CharField(choices=[('holiday', '휴원'), ('academic', '정규수업'), ('competition', '대회'), ('seminar', '특강/세미나')], default='academic', max_length=20, verbose_name='일정 유형'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='start_date',
            field=models.DateTimeField(verbose_name='시작일시'),
        ),
        migrations.CreateModel(
            name='ScheduleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='schedule/attachments/', verbose_name='첨부 파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='arcade.scheduleevent', verbose_name='일정')),
            ],
            options={
                'verbose_name': '첨부 파일',
                'verbose_name_plural': '첨부 파일',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
