# Generated by Django 4.2.29 on 2026-05-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0015_scheduleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schedule/posters/', verbose_name='이미지 (포스터)'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='event_type',
            field=models.CharField(choices=[('holiday', '휴원'), ('academic', '정규수업'), ('competition', '대회'), ('seminar', '특강/세미나')], default='academic', max_length=20, verbose_name='일정 유형'),
        ),
    ]
