# Generated by Django 4.2.29 on 2026-05-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0016_scheduleevent_external_url_scheduleevent_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleevent',
            options={'ordering': ['start_date', 'start_time', 'title'], 'verbose_name': '학원 일정', 'verbose_name_plural': '학원 일정'},
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='0:일, 1:월, 2:화, 3:수, 4:목, 5:금, 6:토 (콤마로 구분)', max_length=50, verbose_name='반복 요일'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='종료 시간'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='시작 시간'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료일시'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='event_type',
            field=models.CharField(choices=[('holiday', '휴원'), ('academic', '정규수업'), ('seminar', '특강/세미나'), ('competition', '대회'), ('certification', '자격시험')], default='academic', max_length=20, verbose_name='일정 유형'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='external_url',
            field=models.URLField(blank=True, help_text='대회페이지나 관련 자료 링크', max_length=500, verbose_name='링크 URL'),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='시작일시'),
        ),
    ]
