# Generated by Django 4.2.29 on 2026-06-12 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0017_alter_scheduleevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목 (게시물용)')),
                ('student_name', models.CharField(max_length=50, verbose_name='학생 이름')),
                ('competition_name', models.CharField(max_length=100, verbose_name='대회명')),
                ('award_name', models.CharField(max_length=50, verbose_name='상격 (예: 대상, 금상)')),
                ('date_awarded', models.DateField(verbose_name='수상일자')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='awards/', verbose_name='대표 이미지')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '대회수상',
                'verbose_name_plural': '대회수상',
                'ordering': ['-date_awarded', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목 (게시물용)')),
                ('student_name', models.CharField(max_length=50, verbose_name='학생 이름')),
                ('cert_name', models.CharField(max_length=100, verbose_name='자격증명')),
                ('date_acquired', models.DateField(verbose_name='취득일자')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='certs/', verbose_name='자격증/배지 이미지')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '자격취득',
                'verbose_name_plural': '자격취득',
                'ordering': ['-date_acquired', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/', verbose_name='첨부파일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
