# Generated by Django 4.2.29 on 2026-06-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0018_award_certification_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='수여기관'),
        ),
        migrations.AddField(
            model_name='certification',
            name='issuer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='발급기관'),
        ),
    ]
