# Generated by Django 4.2.29 on 2026-06-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0019_award_organization_certification_issuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='제목 (게시물용)'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='제목 (게시물용)'),
        ),
    ]
