# Generated by Django 5.1.5 on 2026-06-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0020_alter_award_title_alter_certification_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='자격증명')),
                ('issuer', models.CharField(blank=True, max_length=100, null=True, verbose_name='발급기관')),
                ('description', models.TextField(blank=True, null=True, verbose_name='자격내용 및 소개')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='certinfo/', verbose_name='대표 이미지(로고 등)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='관련 링크')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '자격종류',
                'verbose_name_plural': '자격종류',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
