# Generated by Django 4.2.29 on 2026-06-15 09:24

from django.db import migrations, models
import django.db.models.deletion


def backfill_types(apps, schema_editor):
    Award = apps.get_model('arcade', 'Award')
    Certification = apps.get_model('arcade', 'Certification')
    CertInfo = apps.get_model('arcade', 'CertInfo')
    CompetitionType = apps.get_model('arcade', 'CompetitionType')

    competition_map = {}
    for award in Award.objects.all():
        name = (award.competition_name or '').strip()
        if not name:
            continue
        key = (name, (award.organization or '').strip())
        competition_type = competition_map.get(key)
        if competition_type is None:
            competition_type, _ = CompetitionType.objects.get_or_create(
                name=name,
                organization=(award.organization or '').strip() or None,
            )
            competition_map[key] = competition_type
        award.competition_type_id = competition_type.id
        award.save(update_fields=['competition_type'])

    cert_map = {}
    for cert in Certification.objects.all():
        name = (cert.cert_name or '').strip()
        if not name:
            continue
        key = (name, (cert.issuer or '').strip())
        cert_info = cert_map.get(key)
        if cert_info is None:
            cert_info, _ = CertInfo.objects.get_or_create(
                name=name,
                issuer=(cert.issuer or '').strip() or None,
            )
            cert_map[key] = cert_info
        cert.cert_info_id = cert_info.id
        cert.save(update_fields=['cert_info'])


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0021_certinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='대회명')),
                ('organization', models.CharField(blank=True, max_length=100, null=True, verbose_name='주최/주관')),
                ('description', models.TextField(blank=True, null=True, verbose_name='대회 소개')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='competition_types/', verbose_name='대표 이미지(포스터/로고)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='관련 링크')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '대회종류',
                'verbose_name_plural': '대회종류',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certification',
            name='cert_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='arcade.certinfo', verbose_name='자격종류'),
        ),
        migrations.AddField(
            model_name='award',
            name='competition_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='arcade.competitiontype', verbose_name='대회종류'),
        ),
        migrations.RunPython(backfill_types, migrations.RunPython.noop),
    ]
