# Generated by Django 4.2.29 on 2026-07-04 02:16

from django.db import migrations, models


def populate_contests(apps, schema_editor):
    Contest = apps.get_model('arcade', 'Contest')
    contests_data = [
        {
            'title': '제6회 한국코드페어 (Korea Code Fair)',
            'organizer': '과학기술정보통신부',
            'category': '코딩, 소프트웨어, 알고리즘',
            'target_audience': '초·중·고등학생',
            'start_date': '2026-07-01',
            'end_date': '2026-08-31',
            'link': 'https://koreacodefair.kr',
            'description': '과학기술정보통신부가 주최하고 한국정보과학진흥협회가 주관하는 국내 최대 규모의 청소년 소프트웨어 공모전 및 해커톤 대회입니다. 청소년들이 소프트웨어를 활용하여 실생활의 문제를 창의적으로 해결하는 SW빌더스 대회가 진행됩니다.',
            'is_active': True,
        },
        {
            'title': '제43회 한국정보올림피아드 (KOI)',
            'organizer': '한국정보과학회',
            'category': '코딩, 알고리즘, 소프트웨어',
            'target_audience': '초·중·고등학생',
            'start_date': '2026-08-01',
            'end_date': '2026-09-10',
            'link': 'https://www.digitalculture.or.kr',
            'description': '수학적 논리력과 논리적 사고력을 바탕으로 주어진 알고리즘 문제를 C++, Python 등의 언어로 프로그래밍하여 해결하는 국내 청소년 대상 최고 권위의 알고리즘 대회입니다.',
            'is_active': True,
        },
        {
            'title': '제15회 스마틴 앱+ 챌린지 (STAC 2026)',
            'organizer': '중소벤처기업부, SK플래닛',
            'category': '앱개발, 게임, AI, 소프트웨어',
            'target_audience': '전국 고등학생 및 청소년',
            'start_date': '2026-05-01',
            'end_date': '2026-07-25',
            'link': 'https://www.stac.kr',
            'description': '청소년들의 창의적인 모바일 아이디어를 발굴하고 실무 개발 능력을 키우는 청소년 모바일 앱 및 게임 개발 공모전입니다. 수상 팀에게는 전문가 멘토링, 특허 출원 지원, 해외 연수 등의 풍성한 혜택이 제공됩니다.',
            'is_active': True,
        },
        {
            'title': '넷마블 게임아카데미 제9회 전시회 및 공모전',
            'organizer': '넷마블문화재단',
            'category': '게임, 소프트웨어, 그래픽, 코딩',
            'target_audience': '만 13세~18세 청소년',
            'start_date': '2026-06-10',
            'end_date': '2026-08-20',
            'link': 'https://www.netmarblefoundation.org',
            'description': '미래의 게임 산업 인재를 꿈꾸는 청소년들이 직접 모바일 게임을 기획하고 디자인, 개발한 결과물을 출품하여 경쟁하는 공모전입니다. 수상 작품은 실제 넷마블 게임아카데미 전시회에서 일반인들을 대상으로 선보이게 됩니다.',
            'is_active': True,
        },
        {
            'title': '2026 전국 청소년 과학페어 (융합과학/로봇)',
            'organizer': '과학기술정보통신부, 한국과학창의재단',
            'category': '로봇, 융합과학, 과학기술',
            'target_audience': '초·중·고등학생 (2인 1팀)',
            'start_date': '2026-07-05',
            'end_date': '2026-09-05',
            'link': 'https://www.kofac.re.kr',
            'description': '청소년들이 팀을 이루어 실생활 속의 문제 상황을 과학, 기술, 공학, 예술, 수학(STEAM) 분야의 융합적 사고를 통해 해결하고, 과학적 설계를 기반으로 메카트로닉스나 로봇 기기를 실제로 제작하여 해결하는 융합 과학 축제입니다.',
            'is_active': True,
        },
        {
            'title': '마이크로소프트 이매진컵 주니어 2026 (MS Imagine Cup Junior)',
            'organizer': '마이크로소프트 (Microsoft)',
            'category': 'AI, 소프트웨어, 빅데이터',
            'target_audience': '만 13세~18세 청소년',
            'start_date': '2026-07-01',
            'end_date': '2026-10-15',
            'link': 'https://imaginecup.microsoft.com/junior',
            'description': '글로벌 정보통신 기술 선도 기업 마이크로소프트가 주최하는 세계 청소년 AI 아이디어 경진대회입니다. 인공지능(AI) 기술과 디자인 싱킹 기법을 접목하여 기후변화, 교육 불평등, 건강 증진 등 다양한 사회 문제를 해결하기 위한 기술적 해결책을 제안합니다.',
            'is_active': True,
        }
    ]
    for contest in contests_data:
        Contest.objects.get_or_create(**contest)


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0024_award_competition_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='공모전명')),
                ('organizer', models.CharField(max_length=100, verbose_name='주최/주관')),
                ('category', models.CharField(help_text='AI, 게임, 코딩, 로봇, 소프트웨어 등 콤마(,)로 구분', max_length=100, verbose_name='분야')),
                ('target_audience', models.CharField(max_length=100, verbose_name='참가 대상')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='접수 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='접수 마감일')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='contests/', verbose_name='포스터/대표 이미지')),
                ('link', models.URLField(blank=True, null=True, verbose_name='관련 링크')),
                ('description', models.TextField(blank=True, verbose_name='공모전 소개 및 상세 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '추천 공모전',
                'verbose_name_plural': '추천 공모전',
                'ordering': ['end_date', '-created_at'],
            },
        ),
        migrations.RunPython(populate_contests),
    ]

