# Generated by Django 4.2.29 on 2026-07-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0026_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='certinfo',
            name='category',
            field=models.CharField(blank=True, choices=[('block_coding', '블록코딩'), ('python', '파이썬코딩'), ('ai', 'AI'), ('robot', '로봇')], max_length=20, null=True, verbose_name='분류'),
        ),
        migrations.AddField(
            model_name='certinfo',
            name='target_grades',
            field=models.CharField(blank=True, default='', help_text='ex) elem_1_2,elem_3_4', max_length=200, verbose_name='대상 학년(콤마구분)'),
        ),
    ]
