# Generated by Django 4.2.29 on 2026-07-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0027_certinfo_category_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='certinfo',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='목록 카드에 표시할 이름 (비워두면 name 사용). 예) COS Entry 1~4급', max_length=150, verbose_name='카드 표시명'),
        ),
        migrations.AddField(
            model_name='certinfo',
            name='grade_info',
            field=models.JSONField(blank=True, help_text='[{"grade":"3급","content":"평가내용","target":"추천대상"}, ...]', null=True, verbose_name='등급표 (JSON)'),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='category',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('block_coding', '블록코딩'), ('python', '파이썬코딩'), ('robot', '로봇'), ('doc_work', '문서작업')], max_length=20, null=True, verbose_name='분류'),
        ),
    ]
