# Generated by Django 4.2.29 on 2026-07-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0028_certinfo_display_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='certinfo',
            name='is_national_cert',
            field=models.BooleanField(default=False, verbose_name='국가공인 자격증'),
        ),
    ]
