# Generated by Django 4.2.29 on 2026-08-04 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0029_certinfo_national_cert'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '아바타 임시저장',
                'verbose_name_plural': '아바타 임시저장',
            },
        ),
    ]
