# Generated by Django 4.2.29 on 2026-08-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0030_avatar_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('notices', '공지/일정'), ('learning', '러닝센터')], max_length=20, verbose_name='섹션')),
                ('emoji', models.CharField(default='', max_length=10, verbose_name='이모지')),
                ('name', models.CharField(max_length=50, verbose_name='메뉴 이름')),
                ('url_name', models.CharField(blank=True, help_text='Django URL 이름 (예: board_notice, ai_favorites)', max_length=100, verbose_name='URL 이름')),
                ('url_extra', models.CharField(blank=True, help_text='URL 뒤에 붙일 내용 (예: #works)', max_length=200, verbose_name='URL 추가')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_accent', models.BooleanField(default=False, verbose_name='강조색 (노란색)')),
                ('new_tab', models.BooleanField(default=False, verbose_name='새 탭으로 열기')),
            ],
            options={
                'verbose_name': '네비게이션 메뉴',
                'verbose_name_plural': '네비게이션 메뉴',
                'ordering': ['section', 'order', 'id'],
            },
        ),
    ]
