# Generated by Django 4.2.29 on 2026-08-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0033_nav_item_rename_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='키')),
                ('value', models.TextField(blank=True, verbose_name='값')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
    ]
