# Generated by Django 4.2.29 on 2026-08-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0034_site_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20, verbose_name='팀명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '문제찾기 팀방',
                'verbose_name_plural': '문제찾기 팀방',
                'db_table': 'problem_room',
            },
        ),
        migrations.CreateModel(
            name='ProblemMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('session_key', models.CharField(db_index=True, max_length=64, verbose_name='세션키')),
                ('data', models.JSONField(default=dict, verbose_name='선택 데이터')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='최근 접속')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='arcade.problemroom', verbose_name='팀방')),
            ],
            options={
                'verbose_name': '문제찾기 팀원',
                'verbose_name_plural': '문제찾기 팀원',
                'db_table': 'problem_member',
                'unique_together': {('room', 'session_key')},
            },
        ),
    ]
