# Generated by Django 4.2.29 on 2026-08-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0035_problem_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmember',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='조장'),
        ),
    ]
