# Generated by Django 4.2.29 on 2026-08-10 08:20

import arcade.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0036_add_leader_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='방 이름')),
                ('status', models.CharField(choices=[('waiting', '대기중'), ('voting', '투표중'), ('done', '완료')], default='waiting', max_length=10, verbose_name='상태')),
                ('current_index', models.IntegerField(default=-1, verbose_name='현재 포스터 인덱스')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '작품 평가단 방',
                'verbose_name_plural': '작품 평가단 방',
                'db_table': 'gallery_room',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=arcade.models._gallery_upload_path, verbose_name='이미지')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='제목')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='arcade.galleryroom')),
            ],
            options={
                'verbose_name': '포스터',
                'verbose_name_plural': '포스터',
                'db_table': 'gallery_poster',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=30, verbose_name='투표자 이름')),
                ('voter_session', models.CharField(max_length=64, verbose_name='세션키')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='arcade.galleryposter')),
            ],
            options={
                'verbose_name': '투표',
                'verbose_name_plural': '투표',
                'db_table': 'gallery_vote',
                'unique_together': {('poster', 'voter_session')},
            },
        ),
    ]
