# Generated by Django 4.2.29 on 2026-08-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0037_gallery_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('session_key', models.CharField(max_length=64, verbose_name='세션키')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='arcade.galleryroom')),
            ],
            options={
                'verbose_name': '평가단 참여자',
                'verbose_name_plural': '평가단 참여자',
                'db_table': 'gallery_member',
                'unique_together': {('room', 'session_key')},
            },
        ),
    ]
