# Generated by Django 4.2.29 on 2026-08-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0038_gallery_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryvote',
            name='score',
            field=models.IntegerField(default=5, verbose_name='별점'),
        ),
    ]
