# Generated by Django 4.2.29 on 2026-08-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0039_gallery_vote_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='항목명')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('max_score', models.PositiveIntegerField(default=20, verbose_name='배점')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='arcade.galleryroom')),
            ],
            options={
                'verbose_name': '평가항목',
                'verbose_name_plural': '평가항목',
                'db_table': 'gallery_criteria',
                'ordering': ['order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='galleryvote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='galleryvote',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='arcade.gallerycriteria'),
        ),
        migrations.AlterUniqueTogether(
            name='galleryvote',
            unique_together={('poster', 'voter_session', 'criteria')},
        ),
    ]
