# Generated by Django 4.2.29 on 2026-08-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0040_gallery_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryroom',
            name='poster_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='포스터 시작 시각'),
        ),
        migrations.AddField(
            model_name='galleryroom',
            name='vote_duration',
            field=models.IntegerField(default=0, verbose_name='평가 시간(초)'),
        ),
    ]
