# Generated by Django 4.2.29 on 2026-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0047_satisfactionresponse_motivations'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='급수'),
        ),
    ]
