# Generated by Django 4.2.29 on 2026-08-22 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0048_add_grade_to_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('cert', '자격시험'), ('contest', '대회')], default='cert', max_length=10, verbose_name='종류')),
                ('event_name', models.CharField(max_length=200, verbose_name='대회/자격시험명')),
                ('exam_date', models.DateField(verbose_name='시험/대회 날짜')),
                ('exam_time', models.TimeField(blank=True, null=True, verbose_name='시간')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('cert_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arcade.certinfo', verbose_name='자격종류 (연결)')),
                ('competition_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arcade.competitiontype', verbose_name='대회종류 (연결)')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_exams', to=settings.AUTH_USER_MODEL, verbose_name='등록 관리자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '대회/자격 접수 이력',
                'verbose_name_plural': '대회/자격 접수 이력',
                'ordering': ['exam_date', 'exam_time', '-created_at'],
            },
        ),
    ]
