# Generated by Django 4.2.29 on 2026-08-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0049_add_examregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='competition_base_name',
            field=models.CharField(blank=True, help_text='예: 전국 학생 코딩 경진 대회', max_length=120, verbose_name='대회 기본명 (회차 제외)'),
        ),
        migrations.AddField(
            model_name='scheduleevent',
            name='competition_edition',
            field=models.PositiveSmallIntegerField(blank=True, help_text='예: 4 → 제4회', null=True, verbose_name='회차'),
        ),
    ]
