# Generated by Django 4.2.29 on 2026-08-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0050_add_competition_edition_to_scheduleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='children_info',
            field=models.JSONField(blank=True, null=True, verbose_name='자녀 정보 (JSON)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_attendance',
            field=models.BooleanField(default=True, verbose_name='출석 알림 수신'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_news',
            field=models.BooleanField(default=True, verbose_name='소식 알림 수신'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=True, verbose_name='추가정보 입력 완료'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', '학생회원'), ('parent', '학부모회원'), ('general', '일반회원'), ('teacher', '강사회원'), ('medulab_member', '메듀랩 학생'), ('medulab_parent', '메듀랩 학부모'), ('medulab_staff', '메듀랩스텝'), ('medulab_teacher', '메듀랩 강사')], default='general', max_length=20, verbose_name='회원 유형'),
        ),
    ]
