# Generated by Django 4.2.29 on 2026-08-25 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0051_userprofile_address_userprofile_children_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='수업명')),
                ('days_of_week', models.CharField(blank=True, help_text='0:일, 1:월, 2:화, 3:수, 4:목, 5:금, 6:토 (콤마로 구분)', max_length=50, verbose_name='수업 요일')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('tuition_fee', models.PositiveIntegerField(default=0, verbose_name='수업비 (월, 원)')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='운영 중')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='담당 강사')),
            ],
            options={
                'verbose_name': '수업',
                'verbose_name_plural': '수업',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateField(auto_now_add=True, verbose_name='배정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='수강 중')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='arcade.schoolclass', verbose_name='수업')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
            ],
            options={
                'verbose_name': '수업 배정',
                'verbose_name_plural': '수업 배정',
                'ordering': ['-enrolled_at'],
                'unique_together': {('school_class', 'student')},
            },
        ),
    ]
