# Generated by Django 4.2.29 on 2026-08-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0052_schoolclass_classenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='수업 시간(분)'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='end_time',
            field=models.TimeField(blank=True, help_text='시작 시간 + 수업 시간(분)으로 자동 계산됩니다.', null=True, verbose_name='종료 시간'),
        ),
    ]
