# Generated by Django 4.2.29 on 2026-08-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0053_schoolclass_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='regular_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='정가 (월, 원)'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=90, verbose_name='수업 시간(분)'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='tuition_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='할인가 (월, 원)'),
        ),
    ]
