# Generated by Django 4.2.29 on 2026-08-25 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0054_schoolclass_regular_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='연결일')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL, verbose_name='자녀(학생)')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='연결한 관리자')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to=settings.AUTH_USER_MODEL, verbose_name='학부모')),
            ],
            options={
                'verbose_name': '학부모-자녀 연결',
                'verbose_name_plural': '학부모-자녀 연결',
                'ordering': ['-created_at'],
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
