# Generated by Django 4.2.29 on 2026-08-25 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0055_parentchildlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone_number', models.CharField(max_length=20, verbose_name='연락처')),
                ('message', models.TextField(blank=True, verbose_name='문의 내용')),
                ('is_handled', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수일')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consult_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='작성 회원')),
            ],
            options={
                'verbose_name': '상담 문의',
                'verbose_name_plural': '상담 문의',
                'ordering': ['-created_at'],
            },
        ),
    ]
