# Generated by Django 4.2.29 on 2026-08-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0056_consultinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='schedule_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_class', to='arcade.scheduleevent', verbose_name='연결된 일정'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='show_on_schedule',
            field=models.BooleanField(default=False, help_text='체크하면 학원 일정(정규수업) 페이지에 자동으로 표시됩니다.', verbose_name='정규수업 일정에 표시'),
        ),
    ]
