# Generated by Django 4.2.29 on 2026-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0057_schoolclass_schedule_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('student', '학생회원'), ('parent', '학부모회원'), ('general', '일반회원'), ('teacher', '강사회원'), ('medulab_member', '메듀랩 학생'), ('medulab_parent', '메듀랩 학부모'), ('medulab_staff', '메듀랩스텝'), ('medulab_inactive', '메듀랩 미수강생'), ('medulab_teacher', '메듀랩 강사')], default='general', max_length=20, verbose_name='회원 유형'),
        ),
    ]
