# Generated by Django 4.2.29 on 2026-08-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0058_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '수업', 'verbose_name_plural': '수업'},
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='표시 순서'),
        ),
    ]
