# Generated by Django 4.2.29 on 2026-08-26 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0059_alter_schoolclass_options_schoolclass_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='청구 금액(원)')),
                ('due_date', models.DateField(verbose_name='납부 기한')),
                ('status', models.CharField(choices=[('unpaid', '미납'), ('paid', '완납'), ('canceled', '취소')], default='unpaid', max_length=10, verbose_name='상태')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 완료 일시')),
                ('portone_payment_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='포트원 결제건 ID')),
                ('portone_pay_method', models.CharField(blank=True, max_length=30, verbose_name='결제 수단')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='arcade.schoolclass', verbose_name='수업')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_invoices', to=settings.AUTH_USER_MODEL, verbose_name='학생')),
            ],
            options={
                'verbose_name': '학원비 청구서',
                'verbose_name_plural': '학원비 청구서',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
    ]
