# Generated by Django 4.2.29 on 2026-08-27 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0060_tuitioninvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='monthly_sessions',
            field=models.PositiveIntegerField(default=8, help_text='수업비를 이 횟수로 나눠 회당 단가를 계산합니다 (결석 차감에 사용).', verbose_name='월 기본 출석 횟수'),
        ),
        migrations.AddField(
            model_name='tuitioninvoice',
            name='absence_count',
            field=models.PositiveIntegerField(default=0, verbose_name='전월 결석 횟수'),
        ),
        migrations.AddField(
            model_name='tuitioninvoice',
            name='absence_deduction',
            field=models.PositiveIntegerField(default=0, verbose_name='결석 차감액(원)'),
        ),
        migrations.AddField(
            model_name='tuitioninvoice',
            name='base_amount',
            field=models.PositiveIntegerField(default=0, help_text='결석 차감 전 기본 수업비', verbose_name='정상 수업비(원)'),
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='수업일')),
                ('is_present', models.BooleanField(default=True, verbose_name='출석')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='arcade.classenrollment', verbose_name='수업 배정')),
            ],
            options={
                'verbose_name': '수업 출석',
                'verbose_name_plural': '수업 출석',
                'ordering': ['-date'],
                'unique_together': {('enrollment', 'date')},
            },
        ),
    ]
