# Generated by Django 4.2.29 on 2026-08-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0063_backfill_invoice_base_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('access', '접속'), ('present', '출석'), ('makeup', '보강')], default='access', max_length=10, verbose_name='구분'),
        ),
    ]
