# Generated by Django 4.2.29 on 2026-08-29 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0064_attendance_attendance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionBatchPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='결제 금액(원)')),
                ('status', models.CharField(choices=[('unpaid', '미납'), ('paid', '완납'), ('canceled', '취소')], default='unpaid', max_length=10, verbose_name='상태')),
                ('portone_payment_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='포트원 결제건 ID')),
                ('portone_pay_method', models.CharField(blank=True, max_length=30, verbose_name='결제 수단')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='결제 완료 일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('invoices', models.ManyToManyField(related_name='batch_payments', to='arcade.tuitioninvoice', verbose_name='포함된 청구서')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_batch_payments', to=settings.AUTH_USER_MODEL, verbose_name='결제자(학부모)')),
            ],
            options={
                'verbose_name': '학원비 일괄결제',
                'verbose_name_plural': '학원비 일괄결제',
                'ordering': ['-created_at'],
            },
        ),
    ]
