# Generated by Django 4.2.29 on 2026-09-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0065_tuitionbatchpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, default='', verbose_name='액세스 토큰')),
                ('ig_user_id', models.CharField(blank=True, default='', max_length=50, verbose_name='인스타그램 비즈니스 계정 ID')),
                ('app_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Meta 앱 ID')),
                ('app_secret', models.CharField(blank=True, default='', max_length=100, verbose_name='Meta 앱 시크릿')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='토큰 만료 예정일시')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화 시각')),
                ('last_sync_error', models.CharField(blank=True, default='', max_length=300, verbose_name='마지막 동기화 오류')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '인스타그램 연동 설정',
                'verbose_name_plural': '인스타그램 연동 설정',
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=64, unique=True, verbose_name='미디어 ID')),
                ('media_type', models.CharField(blank=True, default='', max_length=20, verbose_name='미디어 유형')),
                ('media_url', models.URLField(blank=True, default='', max_length=500, verbose_name='미디어 URL')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500, verbose_name='썸네일 URL(동영상용)')),
                ('permalink', models.URLField(blank=True, default='', max_length=500, verbose_name='인스타그램 링크')),
                ('caption', models.TextField(blank=True, default='', verbose_name='캡션')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='게시일시')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='동기화 시각')),
            ],
            options={
                'verbose_name': '인스타그램 게시물',
                'verbose_name_plural': '인스타그램 게시물',
                'ordering': ['-posted_at'],
            },
        ),
    ]
