# Generated by Django 4.2.29 on 2026-09-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0067_add_gallery_nav_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='carousel_children',
            field=models.JSONField(blank=True, help_text='[{"media_type":"IMAGE","media_url":"...","thumbnail_url":"..."}, ...]', null=True, verbose_name='여러 장(캐러셀) 하위 미디어 목록'),
        ),
    ]
