# Generated by Django 4.2.29 on 2026-09-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0068_instagrampost_carousel_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='manual_category',
            field=models.CharField(blank=True, default='', help_text='관리자가 직접 배정한 카테고리 코드. 비어 있으면 캡션 키워드로 자동 분류됨.', max_length=20, verbose_name='수동 지정 필터 카테고리'),
        ),
    ]
