# Generated by Django 4.2.29 on 2026-09-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0069_instagrampost_manual_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='인스타그램 프로필 상단 고정 게시물 등, 학원 갤러리에는 노출하지 않을 게시물', verbose_name='갤러리에서 제외'),
        ),
    ]
