# Generated by Django 4.2.29 on 2026-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0070_instagrampost_is_excluded'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoNotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='기본', max_length=50, verbose_name='라벨')),
                ('access_token', models.TextField(verbose_name='액세스 토큰')),
                ('refresh_token', models.TextField(verbose_name='리프레시 토큰')),
                ('expires_at', models.DateTimeField(verbose_name='액세스 토큰 만료일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 중')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '카카오 알림 토큰',
                'verbose_name_plural': '카카오 알림 토큰',
            },
        ),
        migrations.AddField(
            model_name='consultinquiry',
            name='age_or_grade',
            field=models.CharField(blank=True, help_text='본인 신청일 때만 사용', max_length=30, verbose_name='나이/학년'),
        ),
        migrations.AddField(
            model_name='consultinquiry',
            name='applicant_type',
            field=models.CharField(choices=[('self', '본인'), ('parent', '학부모')], default='self', max_length=10, verbose_name='신청자 구분'),
        ),
        migrations.AddField(
            model_name='consultinquiry',
            name='children_info',
            field=models.JSONField(blank=True, default=list, help_text='학부모 신청일 때 사용. [{"name": "자녀이름", "age": "나이/학년"}, ...]', verbose_name='자녀 정보'),
        ),
        migrations.AddField(
            model_name='consultinquiry',
            name='finder_track',
            field=models.CharField(blank=True, max_length=50, verbose_name='프로그램 찾기 추천 트랙'),
        ),
    ]
