# Generated by Django 4.2.29 on 2026-09-08 14:51

import arcade.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0071_kakaonotifytoken_consultinquiry_age_or_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUploadDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_draft', models.TextField(blank=True, verbose_name='AI 생성 캡션(수정 가능)')),
                ('user_context', models.TextField(blank=True, verbose_name='업로드 시 참고 내용')),
                ('status', models.CharField(choices=[('draft', '검토중'), ('published', '게시완료'), ('failed', '실패')], default='draft', max_length=20, verbose_name='상태')),
                ('published_media_id', models.CharField(blank=True, default='', max_length=64, verbose_name='게시된 인스타그램 미디어 ID')),
                ('published_permalink', models.URLField(blank=True, default='', max_length=500, verbose_name='게시된 인스타그램 링크')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='실패 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_upload_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '인스타 AI 업로드 초안',
                'verbose_name_plural': '인스타 AI 업로드 초안',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramUploadDraftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('media_type', models.CharField(choices=[('IMAGE', '이미지'), ('VIDEO', '영상')], max_length=10, verbose_name='미디어 유형')),
                ('original_file', models.FileField(upload_to=arcade.models._instagram_upload_original_path, verbose_name='원본 파일')),
                ('final_file', models.FileField(blank=True, upload_to=arcade.models._instagram_upload_final_path, verbose_name='게시용 파일')),
                ('has_face', models.BooleanField(default=False, verbose_name='얼굴 감지됨')),
                ('ai_description', models.TextField(blank=True, verbose_name='AI 분석 설명')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arcade.instagramuploaddraft')),
            ],
            options={
                'verbose_name': '인스타 AI 업로드 초안 항목',
                'verbose_name_plural': '인스타 AI 업로드 초안 항목',
                'ordering': ['order', 'id'],
            },
        ),
    ]
