# Generated by Django 4.2.29 on 2026-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0072_instagramuploaddraft_instagramuploaddraftitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconfig',
            name='last_attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화 시도 시각(성공/실패 무관)'),
        ),
    ]
