# Generated by Django 4.2.29 on 2026-09-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0073_instagramconfig_last_attempted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureCareerSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='이름')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='진행 데이터(lesson1Data~lesson12Data)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 저장 시각')),
            ],
            options={
                'verbose_name': '미래직업영상 저장',
                'verbose_name_plural': '미래직업영상 저장',
            },
        ),
    ]
