# Generated by Django 4.2.29 on 2026-09-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0074_futurecareersave'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurecareersave',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='futurecareersave',
            name='name',
            field=models.CharField(max_length=50, verbose_name='이름'),
        ),
        migrations.AlterUniqueTogether(
            name='futurecareersave',
            unique_together={('name', 'grade')},
        ),
    ]
