# Generated by Django 4.2.29 on 2026-09-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0075_futurecareersave_grade_alter_futurecareersave_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='futurecareersave',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='futurecareersave',
            name='birthdate',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='생년월일'),
        ),
        migrations.AlterUniqueTogether(
            name='futurecareersave',
            unique_together={('name', 'birthdate')},
        ),
        migrations.RemoveField(
            model_name='futurecareersave',
            name='grade',
        ),
    ]
