# Generated by Django 4.2.29 on 2026-09-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0076_alter_futurecareersave_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFinderSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('known_items', models.JSONField(blank=True, default=list, verbose_name='내가 잘 아는 것 3가지')),
                ('liked_items', models.JSONField(blank=True, default=list, verbose_name='내가 좋아하는 것 3가지')),
                ('content_idea', models.TextField(blank=True, default='', verbose_name='콘텐츠 아이디어')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='content_finder/posters/%Y/%m/', verbose_name='포스터 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='제출 시각')),
            ],
            options={
                'verbose_name': '나만의 콘텐츠 찾기 제출',
                'verbose_name_plural': '나만의 콘텐츠 찾기 제출',
                'ordering': ['-created_at'],
            },
        ),
    ]
