# Generated by Django 4.2.29 on 2026-09-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0077_contentfindersubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIdeaThumbnailSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('topic', models.CharField(blank=True, default='', max_length=200, verbose_name='콘텐츠 주제')),
                ('channel', models.CharField(blank=True, default='', max_length=100, verbose_name='채널명')),
                ('chosen_idea', models.TextField(blank=True, default='', verbose_name='선택한 아이디어')),
                ('chosen_title', models.CharField(blank=True, default='', max_length=200, verbose_name='선택한 제목')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='content_idea/thumbnails/%Y/%m/', verbose_name='썸네일 이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='제출 시각')),
            ],
            options={
                'verbose_name': '콘텐츠 아이디어 썸네일 제출',
                'verbose_name_plural': '콘텐츠 아이디어 썸네일 제출',
                'ordering': ['-created_at'],
            },
        ),
    ]
