# Generated by Django 4.2.29 on 2026-09-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0078_contentideathumbnailsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptCardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField(blank=True, default=list, verbose_name='카드 순서(키 목록)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정 시각')),
            ],
            options={
                'verbose_name': 'AI 프롬프트 카드 순서',
                'verbose_name_plural': 'AI 프롬프트 카드 순서',
            },
        ),
    ]
