# Generated by Django 4.2.29 on 2026-09-16 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0079_aipromptcardorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIdeaFinderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='임시저장 데이터')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 저장 시각')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_idea_finder_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '콘텐츠 아이디어 찾기 임시저장',
                'verbose_name_plural': '콘텐츠 아이디어 찾기 임시저장',
            },
        ),
        migrations.CreateModel(
            name='ContentFinderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='임시저장 데이터')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 저장 시각')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_finder_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '콘텐츠 주제 찾기 임시저장',
                'verbose_name_plural': '콘텐츠 주제 찾기 임시저장',
            },
        ),
    ]
