# Generated by Django 4.2.29 on 2026-09-18 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arcade', '0081_contentplandraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelBrandingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='임시저장 데이터')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 저장 시각')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_branding_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '유튜브 채널 만들기 임시저장',
                'verbose_name_plural': '유튜브 채널 만들기 임시저장',
            },
        ),
    ]
