# Generated by Django 4.2.29 on 2026-10-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0082_channelbrandingdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='댓글 수'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='instagramuploaddraft',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='예약 게시 시각'),
        ),
        migrations.AlterField(
            model_name='instagramuploaddraft',
            name='status',
            field=models.CharField(choices=[('draft', '검토중'), ('scheduled', '예약됨'), ('publishing', '게시중'), ('published', '게시완료'), ('failed', '실패')], default='draft', max_length=20, verbose_name='상태'),
        ),
    ]
